[package]
name = "port-knock"
version = "0.1.0"
authors = ["Jiri Zuna <jiri@zunovi.cz>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
